---
title: "test-post"
description: |
  A short description of the post.
author:
  - name: Taylor Dunn
    url: https://twitter.com/TDunn12
date: 05-06-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

Here is some example content.

```{r}
library(dunnr)
library(ggplot2)
library(dplyr)
library(palmerpenguins)
extrafont::loadfonts(device = "win", quiet = TRUE)

p1 <- penguins %>%
  filter(!is.na(bill_length_mm)) %>%
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point(aes(shape = species), size = 3, alpha = 0.5, show.legend = FALSE) +
  geom_smooth(method = "lm", formula = "y ~ x",
              se = FALSE, show.legend = FALSE) +
  labs(title = "Penguin bill dimensions",
       subtitle = "Bill length and depth for different penguin species",
       x = "Bill length (mm)", y = "Bill depth (mm)",
       color = "Penguin species", shape = "Penguin species",
       caption = "Data from the palmerpenguins package.") +
  facet_wrap(~species, nrow = 1)
p1 + theme_td() + scale_color_td()
```

