---
title: "Working with Canada COVID-19 data in R"
description: |
  A short description of the post.
author:
  - name: Taylor Dunn
date: 2021-12-28
params:
  date: 2021-12-28
  slug: "2021-12-28-working-with-canada-covid-19-data-in-r"
categories:
  - R
  - package development
  - COVID-19
output:
  distill::distill_article:
    self_contained: false
    toc: true
---


```{r setup, include=TRUE, code_folding="Setup"}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dunnr)
library(httr)

extrafont::loadfonts(device = "win", quiet = TRUE)
theme_set(theme_td())
set_geom_fonts()
set_palette()
```

```{r}
get_summary <- function(split = c("overall", "province", "region")) {
  split <- match.arg(split)

  api_url <- paste0(
    "https://api.covid19tracker.ca/",
    switch(split,
           overall = "summary",
           province = "summary/split",
           region = "summary/split/hr")
  )
  resp <- httr::GET(api_url)

  if (resp$status_code != 200) {
    stop(paste0("Unsuccessful HTTP response returned: ", resp$status_code))
  }

  data <- httr::content(resp, as = "parsed")

  bind_rows(data$data) %>%
    bind_cols(data["last_updated"]) %>%
    mutate(
      across(matches("^change|total"), as.integer),
      across(matches("date"), as.Date),
      last_updated = as.POSIXct(last_updated)
    )
}
summary_region <- get_summary("region")
```

## Reports

```{r}

api_params <- paste0(
  c(ifelse(fill_dates, "fill_dates=true", "fill_dates=false"),
    date,
  collapse = "&"
  )
param
```


```{r}
get_reports <- function(fill_dates = FALSE, stat = NULL, date = NULL,
                        after = NULL, before = NULL) {
  base_url <- "https://api.covid19tracker.ca/"
  
  api_url <- paste0("https://api.covid19tracker.ca/", "reports")
  
  if (fill_dates) {
    fill_dates <- "fill_dates=true"
  }
  else {
    fill_dates <- NULL
  }
  if (!is.null(stat)) stat <- paste0("stat=", stat)
  if (!is.null(date)) date <- paste0("date=", date)
  if (!is.null(after)) after <- paste0("after=", after)
  if (!is.null(before)) before <- paste0("before=", before)
  
  api_params <- paste(c(fill_dates, stat, date, after, before),
                      collapse = "&")
  
  if (nchar(api_params) > 0) {
    api_url <- paste0(api_url, "?", api_params)
  }
  return(api_url)
  
  resp <- httr::GET(api_url)

  if (resp$status_code != 200) {
    stop(paste0("Unsuccessful HTTP response returned: ", resp$status_code))
  }

  data <- httr::content(resp, as = "parsed")

  bind_rows(data$data) %>%
    bind_cols(data["last_updated"]) %>%
    mutate(
      across(matches("^change|total"), as.integer),
      across(matches("date"), as.Date),
      last_updated = as.POSIXct(last_updated)
    )
}
get_reports(before = "2021-10-10")
```


```{r}
paste0(
    base_url, "reports?",
    ifelse(fill_dates, )
  )
  
}
reports <- get_reports()
reports
get_reports(date = "2021-12-27")
```

```{r}
reports %>%
  ggplot(aes(x = date, y = total_boosters_1)) +
  geom_line() +
  scale_x_date(limits = as.Date(c("2021-03-01", "2022-01-01")))
```

```{r}

```


### Regions

```{r}
get_regions <- function() {
  api_url <- paste0("https://api.covid19tracker.ca/", "regions")
  resp <- httr::GET(api_url)

  if (resp$status_code != 200) {
    stop(paste0("Unsuccessful HTTP response returned: ", resp$status_code))
  }

  data <- httr::content(resp, as = "parsed")

  bind_rows(data$data)
}
regions <- get_regions()
```

```{r}
summary_region %>%
  left_join(
    regions, by = "hr_uid"
  ) %>%
  filter(province == "NS")
```

## Reproducibility {.appendix}

<details><summary>Session info</summary>

```{r echo=FALSE}
devtools::session_info()$platform
devtools::session_info()$packages %>%
  rmarkdown::paged_table()
```

</details>

<details><summary>Git repository</summary>

```{r echo=FALSE}
git2r::repository()
```

</details>

```{r echo=FALSE}
dunnr::get_distill_source(date = params$date, slug = params$slug)
```

