---
title: "Canada COVID-19 data in R: creating a package"
description: |
  Creating an R package that wraps the Canadian COVID-19 tracker API.
author:
  - name: Taylor Dunn
date: 2021-12-30
params:
  date: 2021-12-30
  slug: "2021-12-30-canada-covid-19-data-in-r-creating-a-package"
categories:
  - R
  - COVID-19
  - API
  - package development
output:
  distill::distill_article:
    self_contained: false
    toc: true
---


```{r setup, include=TRUE, code_folding="Setup"}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dunnr)

extrafont::loadfonts(device = "win", quiet = TRUE)
theme_set(theme_td())
set_geom_fonts()
set_palette()
```

## Package

[Naming things](https://www.njtierney.com/post/2018/06/20/naming-things/) is hard.

https://devguide.ropensci.org/building.html#package-name-and-metadata

https://r-pkgs.org/workflows101.html#create-a-package

I'm a fan of the all lowercase names.
Here are some I was considering, and their availability on CRAN, Bioconductor and GitHub:

```{r}
available::available("cancovid", browse = FALSE)
available::available("canadacovid", browse = FALSE)
available::available("cancovidtrackr", browse = FALSE)
```

All of these are available.


```{r}
get_summary <- function(split = c("overall", "province", "region")) {
  split <- match.arg(split)

  api_url <- paste0(
    "https://api.covid19tracker.ca/",
    switch(split,
           overall = "summary",
           province = "summary/split",
           region = "summary/split/hr")
  )
  resp <- httr::GET(api_url)

  if (resp$status_code != 200) {
    stop(paste0("Unsuccessful HTTP response returned: ", resp$status_code))
  }

  data <- httr::content(resp, as = "parsed")

  bind_rows(data$data) %>%
    bind_cols(data["last_updated"]) %>%
    mutate(
      across(matches("^change|total"), as.integer),
      across(matches("date"), as.Date),
      last_updated = as.POSIXct(last_updated)
    )
}
summary_region <- get_summary("region")
```

## Reports

```{r}
get_reports <- function(fill_dates = FALSE, stat = NULL, date = NULL,
                        after = NULL, before = NULL) {
  base_url <- "https://api.covid19tracker.ca/"
  
  api_url <- paste0("https://api.covid19tracker.ca/", "reports")
  
  if (fill_dates) {
    fill_dates <- "fill_dates=true"
  }
  else {
    fill_dates <- NULL
  }
  if (!is.null(stat)) stat <- paste0("stat=", stat)
  if (!is.null(date)) date <- paste0("date=", date)
  if (!is.null(after)) after <- paste0("after=", after)
  if (!is.null(before)) before <- paste0("before=", before)
  
  api_params <- paste(c(fill_dates, stat, date, after, before),
                      collapse = "&")
  
  if (nchar(api_params) > 0) {
    api_url <- paste0(api_url, "?", api_params)
  }
  return(api_url)
  
  resp <- httr::GET(api_url)

  if (resp$status_code != 200) {
    stop(paste0("Unsuccessful HTTP response returned: ", resp$status_code))
  }

  data <- httr::content(resp, as = "parsed")

  bind_rows(data$data) %>%
    bind_cols(data["last_updated"]) %>%
    mutate(
      across(matches("^change|total"), as.integer),
      across(matches("date"), as.Date),
      last_updated = as.POSIXct(last_updated)
    )
}
get_reports(before = "2021-10-10")
```

### Regions

```{r}
get_regions <- function() {
  api_url <- paste0("https://api.covid19tracker.ca/", "regions")
  resp <- httr::GET(api_url)

  if (resp$status_code != 200) {
    stop(paste0("Unsuccessful HTTP response returned: ", resp$status_code))
  }
  if (http_type(resp) != "application/json") {
    stop("API did not return json", call. = FALSE)
  }

  data <- httr::content(resp, as = "parsed")
  bind_rows(data$data)
}
regions <- get_regions()
```

```{r}
summary_region %>%
  left_join(
    regions, by = "hr_uid"
  ) %>%
  filter(province == "NS")
```


## Reproducibility {.appendix}

<details><summary>Session info</summary>

```{r echo=FALSE}
devtools::session_info()$platform
devtools::session_info()$packages %>%
  rmarkdown::paged_table()
```

</details>

<details><summary>Git repository</summary>

```{r echo=FALSE}
git2r::repository()
```

</details>

```{r echo=FALSE}
dunnr::get_distill_source(date = params$date, slug = params$slug)
```

